import Head from "next/head";
import { Button } from "components/elements";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      asdf
      <Button>some text</Button>
    </div>
  );
}
